### ISSUE TITLE
a little problem for add languages

### ISSUE THREAD

**Issue by cadot-info** [DiemenDesign/summernote-classes#2]
Hello and thanks for your great tools ;-)
i will add other languages for your tools.
I have create a new extend of summernote.lang after your 'en-US' but i don't know how use it in webpack

```
import summernote from 'summernote'
require('./summernote-classes/summernote-classes')
require('summernote/lang/summernote-fr-FR')

$(document).ready(function () {
    $('#editorjs_0').summernote({
        lang: 'fr-FR'
    }
    );
})
```
thanks for your help

**Comment by DennisSuitters** [comment]
You could add it directly to the source of the plugin, or if you create a separate file, include it after the plugin. Not sure with using webpack, I don't bother with all these fancy things.

**Comment by cadot-info** [comment]
ok, thanks, i try.

**Comment by cadot-info** [comment]
it's ok in other directory after the call of js.
Thanks ;-)
